version: "3.1"
services:
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus-rules
    ports:
      - "9090:9090"
    labels:
      container_group: "monitoring"
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    env_file:
      - config.monitoring
    labels:
      container_group: "monitoring"
  grafana-init:
    build: grafana-init
    environment:
      - GRAFANA_HOST=grafana:3000
    volumes:
      - ./:/root/app
  aliens:
    image: pyaillet/xeno:1.0
    ports:
      - 8081:8080
    environment:
      - INFECTED_BY_TURN=2
      - MARINE_KILL_BY_TURN=0.2
      - ALIEN_KILL_BY_TURN=0.3
      - LOOP_MILLISECOND_TIMEOUT=1000
    labels:
      container_group: "xenomorphs"      
  alertmanager:
    image: prom/alertmanager:v0.13.0
    volumes:
      - ./alertmanager-config.yml:/etc/alertmanager/config.yml
      - ./aliens.tmpl:/etc/alertmanager/templates/aliens.tmpl
    ports:
      - 9093:9093

volumes:
    prometheus_data: {}
    grafana_data: {}   